---
- name: Ensure required utilities are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - cryptsetup
    - grep
  become: yes
  tags: 
    - encrypt_partition
    - encrypt_second
    - encrypt_root_adjacent

- import_tasks: encrypt_second_disk.yml
  tags: 
    - encrypt_second
    - encrypt_partition
- import_tasks: encrypt_partition_next_to_root.yml
  tags: 
    - encrypt_root_adjacent
    - encrypt_partition
