---
- name: Configure network interface on AWS servers
  hosts: servers
  become: yes
  gather_facts: yes  
  roles:
    - role: manage_interface
      tags:
        - netplan

- name: Encrypt partitions on AWS servers
  hosts: servers
  become: yes
  vars_files:
    - vault.yml
  gather_facts: yes  
  roles:
    - role: encrypt_partitions
      tags:
        - encrypt_second
        - encrypt_root_adjacent

- name: Disable C-states on AWS servers
  hosts: servers
  become: yes
  gather_facts: yes
  roles:
    - role: disable_cstate
      tags:
        - cstate
