---
- name: Configure network interface on AWS servers
  hosts: servers
  become: yes
  gather_facts: yes  
  roles:
    - role: manage_interface
      tags:
        - netplan

- name: Encrypt partitions on AWS servers
  hosts: servers
  become: yes
  vars_files:
    - vault.yml
  gather_facts: yes  
  roles:
    - role: encrypt_partitions
      tags:
        - encrypt_partition

- name: Disable C-states on AWS servers
  hosts: servers
  become: yes
  gather_facts: yes
  roles:
    - role: disable_cstate
      tags:
        - cstate

- name: Switch CPU operation to more productive mode on AWS servers
  hosts: servers
  become: yes
  roles:
    - role: switch_cpu_mode
      tags:
        - switch_cpu_mode
